name: build and push docker

on: push

jobs:
  call-tests:
    name: Test app
    permissions: write-all
    uses: ./.github/workflows/tests.yml
  docker:
    runs-on: ubuntu-latest
    needs: call-tests
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Choose tag
        run: |
            echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            if [ "${GITHUB_REF##*/}" == "main" ]; then
              echo "TAG=latest" >> $GITHUB_ENV
            else
              echo "TAG=${GITHUB_REF##*/}_beta" >> $GITHUB_ENV
            fi
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.TAG }}
          build-args: |
              BRANCH=${{ env.BRANCH }}
