name: tests

on: workflow_call

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build project with Maven
        id: buildApp
        run: |
          cd app
          mvn clean install -DskipTests -Dspotbugs.skip=true

      - name: Run unit tests
        run: |
          cd app
          mvn test
        if: always() && steps.buildApp.outcome == 'success'

      - name: Run spotbugs
        run: |
          cd app
          mvn spotbugs:check@find-bugs
        if: always() && steps.buildApp.outcome == 'success'

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'Example Java app'
          path: './app'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
        if: always() && steps.buildApp.outcome == 'success'

      - name: Set up docker Buildx
        id: setupBuildx
        uses: docker/setup-buildx-action@v3
        if: always()

      - name: Build and export to docker
        id: buildTestImage
        uses: docker/build-push-action@v5
        with:
          context: ./app
          load: true
          tags: testImage
        if: always() && steps.setupBuildx.outcome == 'success'

      - name: Run app
        id: runTestImage
        run: docker run -p 8080:8080 testImage
        if: always() && steps.buildTestImage.outcome == 'success'

      - name: DAST scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080'
          fail_action: false
        if: always() && steps.runTestImage.outcome == 'success'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test_reports
          path: ${{github.workspace}}/reports
        if: always() && steps.buildApp.outcome == 'success'
