name: tests

on: workflow_call

jobs:
  SCA-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build project with Maven and run unit tests
        run: |
          cd app
          mvn clean install

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'Example Java app'
          path: './app'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck_report
          path: ${{github.workspace}}/reports

  #SAST-testing:
  #  runs-on: ubuntu-latest
  #  steps:
  #    -
  #      name: Check out the repo
  #      uses: actions/checkout@v4

  #run-unit-tests:
  #  runs-on: ubuntu-latest
  #  steps:
  #    -
  #      name: Check out the repo
  #      uses: actions/checkout@v4

  #DAST-testing:
  #  runs-on: ubuntu-latest
  #  steps:
  #    -
  #      name: Check out the repo
  #      uses: actions/checkout@v4
