name: tests

on: workflow_call

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build project with Maven
        id: buildApp
        run: |
          cd app
          mvn clean install -DskipTests -Dspotbugs.skip=true

      - name: Run unit tests
        run: |
          cd app
          mvn test
        if: always() && steps.buildApp.outcome == 'success'

      - name: Run spotbugs
        run: |
          cd app
          mvn spotbugs:check@find-bugs
        if: always() && steps.buildApp.outcome == 'success'

      - name: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        run: >
          docker run
          -v ${{github.workspace}}:${{github.workspace}}
          owasp/dependency-check:latest
          --project Example_Java_app
          --scan ${{github.workspace}}/app
          --out ${{github.workspace}}/reports
          --noupdate
          --failOnCVSS 5
          --enableRetired
        if: always() && steps.buildApp.outcome == 'success'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test_reports
          path: ${{github.workspace}}/reports
        if: always() && steps.buildApp.outcome == 'success'
