name: tests

on: workflow_call

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build project with Maven
        id: buildApp
        run: |
          cd app
          mvn clean install -DskipTests

      - name: run unit tests and spotbugs
        run: |
          cd app
          mvn test
        if: always() && steps.buildApp.outcome == 'success'

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'Example Java app'
          path: './app'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
        if: always() && steps.buildApp.outcome == 'success'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck_report
          path: ${{github.workspace}}/reports
        if: always() && steps.Depcheck.outcome == 'success'
